title: Daniel Zhou
author: Daniel Zhou
email: danielzhou930@gmail.com
description: > 
  Welcome to my personal data science and quantitative finance website.
show_excerpts: 

sass:
  sass_dir: _sass
plainwhite:
  name: Daniel Zhou
  tagline: New York | Chicago | Shanghai
  post: View Blog Posts
  date_format: "%b %-d, %Y"
  sitemap: true 

  # generate social links in footer
  social_links:
    github:  danielzzhou
    linkedIn: in/daniel-zhiheng-zhou
    rss: rss


    # Mastodon instances
    mastodon:
    - username: jekyll
      instance: https://danielzzhou.github.io/nu-cmu/
  

# If 
header_pages:
 - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
remote_theme: thelehhman/plainwhite-jekyll
